### ISSUE TITLE
Add CTRL+L Support to clear the terminal

### ISSUE THREAD

**Issue by gabeduke** [jamesburns-rts/teamwork-cli#3]
User should have the ability to clear the terminal window without exiting the program (in interactive mode). CTRL+L is the standard UNIX mapping to redraw the screen it would be nice if this could be used. Alternatively a menu option to clear would still be helpful.

**Comment by gabeduke** [comment]
potential solution:

```javascript
console.reset = function () {
  return process.stdout.write('\033c');
}
```

**Comment by gabeduke** [comment]
I looked around but was unable to find where the user input is parsed. If you can point me in the right direction I can take another look.

**Comment by jamesburns-rts** [comment]
I added a clear screen command: https://github.com/jamesburns-rts/teamwork-cli/commit/60fd33f763d89d7c9f94bd6419e1c53813898b57 although using ctrl-L seems too complicated with the prompt library I'm using.
