### ISSUE TITLE
Search function to isolate Project or Task

### ISSUE THREAD

**Issue by gabeduke** [jamesburns-rts/teamwork-cli#6]
There should be a search function to quickly drill down to the Project or Task to add time to. 
* Should be case insensitive. 
* Should strip characters from search? Or it may be better to have a matching threshold where best match is higher in the response list
* Should work in interactive or cli mode
* Items should be grouped by `Task Lists` and `Tasks` separately, with `Tasks` ranking higher in results

example:

```
$ tw -f stand-up

Tasks:
1) teamwork/RTS - Admin 2017/Discussion/Meeting (no client)/Weekly Stand-up >
2) teamwork/RTS - Some Project 1/Meetings/Daily Standup >

Task Lists:
3) teamwork/RTS - Some Project2/Standups >
```

**Comment by jamesburns-rts** [comment]
This was added a while ago with the `search` command in the interactive mode
